/*
* generated by Xtext
*/
package net.sf.smbt.ez.script;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class EzDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return net.sf.smbt.ez.script.ui.internal.EzDslActivator.getInstance().getInjector("net.sf.smbt.ez.script.EzDsl");
	}
	
}
