/*
* generated by Xtext
*/
package net.sf.smbt.osc.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class OscDslProposalProvider extends AbstractOscDslProposalProvider {

}
