/*
* generated by Xtext
*/
package net.sf.smbt.ez.script.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import net.sf.smbt.ez.script.services.EzDslGrammarAccess;

public class EzDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EzDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected net.sf.smbt.ez.script.parser.antlr.internal.InternalEzDslParser createParser(XtextTokenStream stream) {
		return new net.sf.smbt.ez.script.parser.antlr.internal.InternalEzDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public EzDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EzDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
