/*
* generated by Xtext
*/
package net.sf.smbt.ez.script.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class EzDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
