if(typeof dartCallbackObjects=="undefined")var dartCallbackObjects=new Array;if(typeof dartCreativeDisplayManagers=="undefined")var dartCreativeDisplayManagers=new Object;if(typeof dartMotifAds=="undefined")var dartMotifAds=new Array;if(!self.dartLoadedGlobalTemplates_56_03)self.dartLoadedGlobalTemplates_56_03={};if(self.dartLoadedGlobalTemplates_56_03["inpage"])self.dartLoadedGlobalTemplates_56_03["inpage"].isLoaded=true;
function RichMediaCreativeDisplayManager_56_03(a,b){this.creative=a;this.creativeIdentifier=a.creativeIdentifier;this.previewMode=a.previewMode;this.debugEventsMode=a.debugEventsMode;this.renderingId=a.renderingId;this.creativeType=a.type;this.mtfNoFlush=a.mtfNoFlush;this.dartPopupArray=new Object;this.isDisplayTimerRunning=false;this.fsCommandHandlers=new Object;this.rootElementArray=new Array;this.sourceIframe=typeof b!="undefined"?b:null;this.overlay=null;this.dartEventBin=null;this.previewHandler=
null;this.init(a);dartMotifAds[dartMotifAds.length]=this.creative}RichMediaCreativeDisplayManager_56_03.prototype=new RichMediaCore_56_03;
RichMediaCreativeDisplayManager_56_03.prototype.init=function(a){this.createEventBin(a);this.assets=new Object;for(var b in this.creative.assets)if(!this.isPartOfArrayPrototype(b)){var c=this.creative.assets[b];this.assets[c.variableName]=c}if(a.type==this.CREATIVE_TYPE_FLOATING_WITH_REMINDER||a.type==this.CREATIVE_TYPE_INPAGE_WITH_FLOATING||a.type==this.CREATIVE_TYPE_INPAGE_WITH_OVERLAY)this.dualAssetManager=new DualAssetManager_56_03(a,this);if(a.type==this.CREATIVE_TYPE_EXPANDING||a.type==this.CREATIVE_TYPE_FLOATING||
a.type==this.CREATIVE_TYPE_FLOATING_WITH_REMINDER||a.type==this.CREATIVE_TYPE_INPAGE_WITH_FLOATING)this.pageElementsManager=new PageElementsManager_56_03(a,this)};
RichMediaCreativeDisplayManager_56_03.prototype.createEventBin=function(a){if(!this.previewMode)this.dartEventBin=new RichMediaEventBin_56_03(this.creativeIdentifier,this.mtfNoFlush);else if(this.debugEventsMode){this.initDebugHandler(a);var b=this.getSourceIframe();if(typeof DebugEventBin_56_03!="undefined")this.dartDebugEventBin=new DebugEventBin_56_03(this.creativeIdentifier,this.previewHandler);else if(this.isServedInIframe()&&typeof b.contentWindow.DebugEventBin_56_03!="undefined")this.dartDebugEventBin=
new b.contentWindow.DebugEventBin_56_03(this.creativeIdentifier,this.previewHandler)}};RichMediaCreativeDisplayManager_56_03.prototype.initDebugHandler=function(a){try{if(typeof DARTDebugEventHandler!="undefined")this.previewHandler=new DARTDebugEventHandler;else if(typeof self.parent.DARTDebugEventHandler!="undefined"){self.parent.globalTemplatePreviewHandler=new self.parent.DARTDebugEventHandler;this.previewHandler=self.parent.globalTemplatePreviewHandler}}catch(b){}};
RichMediaCreativeDisplayManager_56_03.prototype.deleteCreative=function(a){this.deleteJSObjects();if(!a)this.deleteHTMLObjects()};RichMediaCreativeDisplayManager_56_03.prototype.deleteHTMLObjects=function(){for(var a=0;a<this.rootElementArray.length;a++)if(this.rootElementArray[a]!=null&&this.rootElementArray[a].parentNode!=null)this.removeChildNode(this.rootElementArray[a],this.rootElementArray[a].parentNode)};
RichMediaCreativeDisplayManager_56_03.prototype.deleteJSObjects=function(){if(this.creative.isInterstitial)DoNotDisplayIA=null;this.detachFSCommandHandler();this.setShouldFlush(this.renderingId,false);this.removeArrayElement(dartCallbackObjects,this.dartEventBin);this.dartEventBin=null};RichMediaCreativeDisplayManager_56_03.prototype.removeArrayElement=function(a,b){for(var c=0;c<a.length;c++)if(a[c]==b)a[c]=null};
RichMediaCreativeDisplayManager_56_03.prototype.fsHook=function(a){var b="";b+=a+"_DoFSCommand = function(command, args) { \n";b+='    if(dartCreativeDisplayManagers["'+this.creativeIdentifier+'"] != null) dartCreativeDisplayManagers["'+this.creativeIdentifier+'"].FSCommandHandler(command, args);\n';b+="}\n";window.eval(b);if(this.isInternetExplorer()){var c=this.toObject(a);var e=eval(a+"_DoFSCommand");this.fsCommandHandlers[a]=e;if(c.attachEvent("FSCommand",e))this.registerPageUnLoadHandler("detachFSCommandHandler()",
this)}};RichMediaCreativeDisplayManager_56_03.prototype.registerFSCommandHandler=function(a){if(this.isInternetExplorer()){var b=this.toObject("FLASH_"+a);var c=this.fsCommandHandlers["FLASH_"+a];if(b.attachEvent("FSCommand",c))this.registerPageUnLoadHandler("detachFSCommandHandler()",this)}};
RichMediaCreativeDisplayManager_56_03.prototype.detachFSCommandHandler=function(){for(var a in this.assets)if(!this.isPartOfArrayPrototype(a)){var b="FLASH_"+a;var c=this.toObject(b);var e=this.fsCommandHandlers[b];if(c!=null)if(this.isInternetExplorer())c.detachEvent("FSCommand",e)}};
RichMediaCreativeDisplayManager_56_03.prototype.FSCommandHandler=function(a,b){if(a=="mtfCommands"){var c=b.split("&");for(var e=0;e<c.length;e++){var d=this._parseCommandString(c[e]);var f=this.createFunctionCall(d.command,d.argArray);try{eval('dartCreativeDisplayManagers["'+this.creativeIdentifier+'"].'+f)}catch(g){f=d.command+"('"+d.argString+"')";try{eval(f)}catch(h){}}}}else{var i=this._splitArgs(b);f=this.createFunctionCall(a,i);try{return eval('dartCreativeDisplayManagers["'+this.creativeIdentifier+
'"].'+f)}catch(j){try{eval(f)}catch(k){}}}};RichMediaCreativeDisplayManager_56_03.prototype.setFocus=function(a){var b=this.toObject("FLASH_"+a);if(b!=null)if(this.isFirefox()&&this.isMac()){var c=this.getFireFoxVersion();if(c>=2&&c<3){b.blur();window.blur()}}};
RichMediaCreativeDisplayManager_56_03.prototype.reportCustomVariable=function(a,b){if(!this.previewMode){var c=this.creative.stringPostingUrl;var e=new Date;c+="&timestamp="+e.getTime()+";"+"str="+unescape(a)+";"+"strtype="+b;var d=document.createElement("img");d.src=c}else{var f=this.getEventBin();if(f!=null)f.logCustomVariable(unescape(a),b)}};
RichMediaCreativeDisplayManager_56_03.prototype.setDynamicServeId=function(a){var b=this.getEventBin();if(b){b.setDynamicServeId(a);var c=this.getStandardEventId(this.STANDARD_EVENT_DYNAMIC_CREATIVE_IMPRESSION);b.logMetEvent("Count",c,this.creative.renderingId,false,this.STANDARD_EVENT_DYNAMIC_CREATIVE_IMPRESSION);b.flushMetCounters(this.creative.renderingId)}};
RichMediaCreativeDisplayManager_56_03.prototype.getFireFoxVersion=function(){var a=navigator.userAgent.toUpperCase();if(a.indexOf("GECKO")!=-1)if(a.indexOf("FIREFOX")!=-1)return parseFloat(a.substr(a.lastIndexOf("/")+1));return null};RichMediaCreativeDisplayManager_56_03.prototype.conduitInitialized=function(a){RichMediaCore_56_03.prototype.trackCsiEvent("fe");var b=this.getAsset(a);b.conduitInitialized=true;if(this.shouldCsi(b,this.creative.type))RichMediaCore_56_03.prototype.reportCsi(this.creative)};
RichMediaCreativeDisplayManager_56_03.prototype.setTimerAdjustment=function(a,b,c){this.getEventBin().setTimerAdjustment(a,b,c)};RichMediaCreativeDisplayManager_56_03.prototype.getEventBin=function(){if(!this.previewMode)return this.dartEventBin;else if(this.debugEventsMode)return this.dartDebugEventBin;else return null};RichMediaCreativeDisplayManager_56_03.prototype.getStandardEventId=function(a){return this.creative.standardEvents[a].reportingId};
RichMediaCreativeDisplayManager_56_03.prototype.getEventId=function(a,b){var c;if(a=="Start"||a=="Stop")c=this.creative.timerEvents[b];else if(a=="Count")c=this.creative.counterEvents[b];else if(a=="Exit")c=this.creative.exitEvents[b];return c!=null?c.reportingId:-1};RichMediaCreativeDisplayManager_56_03.prototype.evaluateBoolean=function(a){var b=typeof a;return b=="string"&&a=="true"||b=="boolean"&&a};
RichMediaCreativeDisplayManager_56_03.prototype.logEvent=function(a,b,c,e,d){var f;b=unescape(b);d=this.evaluateBoolean(d);e=this.evaluateBoolean(e);if(d)f=this.getEventId(a,b);else f=this.getStandardEventId(b);if(f==-1)return;if(a==="Exit")a="Count";if(b==this.STANDARD_EVENT_DISPLAY_TIMER)this.logDisplayTimerEvent(a,c);else{var g=this.getEventBin();if(g)g.logMetEvent(a,f,c,e,b)}};
RichMediaCreativeDisplayManager_56_03.prototype.getCustomVideoEventId=function(a,b,c){var e=this.getStandardEventId(c);var d;if(a=="Start"||a=="Stop")d=this.creative.timerEvents;else d=this.creative.counterEvents;var f="";for(var g in d){var h=d[g];if(h.sourceComponentName==b&&h.sourceStandardEventId==e){f=h.reportingId;break}}return f};
RichMediaCreativeDisplayManager_56_03.prototype.logVideoEvent=function(a,b,c){b=unescape(b);var e=this.creative.videoComponents[b];var d=this.getEventBin();var f=this.getStandardEventId(c);if(d)d.logMetEvent(a,f,this.creative.renderingId,false,c);if(e.trackCustomEvents){var g=this.getCustomVideoEventId(a,b,c);if(d)d.logMetEvent(a,g,this.creative.renderingId,false,c)}};
RichMediaCreativeDisplayManager_56_03.prototype.stopStandardTimers=function(a){this.logEvent("Stop",this.STANDARD_EVENT_DISPLAY_TIMER,a);this.logEvent("Stop",this.STANDARD_EVENT_INTERACTION_TIMER,a);this.logEvent("Stop",this.STANDARD_EVENT_VIDEO_VIEW_TIMER,a)};
RichMediaCreativeDisplayManager_56_03.prototype.logDisplayTimerEvent=function(a,b){var c=this.getEventBin();if(a=="Start"){if(!this.isDisplayTimerRunning){if(c)c.logMetEvent("Start","2",b);this.isDisplayTimerRunning=true}}else if(a=="Stop")if(this.isDisplayTimerRunning){if(c)c.logMetEvent("Stop","2",b);this.isDisplayTimerRunning=false}};RichMediaCreativeDisplayManager_56_03.prototype.flushCounters=function(a){var b=this.getEventBin();if(b)b.flushMetCounters(a)};
RichMediaCreativeDisplayManager_56_03.prototype.scheduleTurnOffEventBinFlushing=function(a,b){var c=this.getEventBin();if(c)this.registerTimeoutHandler(b*1000,"turnOffFlushing('"+a+"')",c)};RichMediaCreativeDisplayManager_56_03.prototype.setShouldFlush=function(a,b){var c=this.getEventBin();if(c)c.setMetShouldFlush(a,b)};RichMediaCreativeDisplayManager_56_03.prototype.getShouldFlush=function(a){var b=this.getEventBin();return b&&b.getShouldFlush(a)};
RichMediaCreativeDisplayManager_56_03.prototype.registerUrl=function(a,b){var c=this.getEventBin();if(c)c.registerEventBinUrl(a,b)};RichMediaCreativeDisplayManager_56_03.prototype.logExitEventFlushCounters=function(a,b,c,e){this.logEvent("Exit",a,b,c,e);this.flushCounters(b)};RichMediaCreativeDisplayManager_56_03.prototype.logEventFlushCounters=function(a,b,c,e,d){this.logExitEventFlushCounters(b,c,e,d)};
RichMediaCreativeDisplayManager_56_03.prototype._logEventFlushCountersOpenPopup=function(a,b,c,e,d,f,g){this.logEvent(a,b,c,true);this.flushCounters(c);this.openPopup(e,d,f,g)};RichMediaCreativeDisplayManager_56_03.prototype.getExitUrl=function(a,b){var c=b==undefined?this.creative.exitEvents[a].url:b;var e=this.creative.clickThroughUrl;var d=this.creative.clickN!=""?parseInt(this.creative.clickN):1;if(e.indexOf("?")>=0||e.indexOf("&")>=0)for(var f=0;f<d;f++)c=escape(c);return e+c};
RichMediaCreativeDisplayManager_56_03.prototype.logInteractiveImpression=function(){if(!this.interactiveImpressionLogged){this.logEvent("Count",this.STANDARD_EVENT_INTERACTIVE_IMPRESSION);this.interactiveImpressionLogged=true}};
RichMediaCreativeDisplayManager_56_03.prototype.logExitFlushEventsOpenPopup=function(a,b,c,e,d,f){var g=this.creative.exitEvents[b];var h=this.getExitUrl(b);d=d=="null"?null:d;f=(f="null")?null:f;if(d)h=this.getExitUrl(b,f);else if(f!=null&&f!=""){h=h.indexOf("?")!=-1&&f.charAt(0)!="&"&&h.charAt(h.length-1)!="?"?h+"&":h;h=h.indexOf("?")==-1&&f.indexOf("?")==-1?h+"?":h;h+=f}this.logInteractiveImpression();this.logExitEventFlushCounters(b,c,true,true);if(g.customizedWindow)this.openPopup(h,"motifWindow",
g.windowFeatures,false);else this.openPopup(h,"motifWindow",null,false)};RichMediaCreativeDisplayManager_56_03.prototype.setExpandingManager=function(a){this.expandingManager=a};RichMediaCreativeDisplayManager_56_03.prototype.hasExpandingManager=function(){return typeof this.expandingManager!="undefined"};RichMediaCreativeDisplayManager_56_03.prototype.setFloatingManager=function(a){this.floatingManager=a};
RichMediaCreativeDisplayManager_56_03.prototype.hasFloatingManager=function(){return typeof this.floatingManager!="undefined"};
RichMediaCreativeDisplayManager_56_03.prototype.expandAsset=function(a){var b=this.getAsset(a);var c=b.expandedWidth!=undefined?b.expandedWidth:b.width;var e=b.expandedHeight!=undefined?b.expandedHeight:b.height;var d=this.creative.type==this.CREATIVE_TYPE_EXPANDING;var f=this.toObject("FLASH_"+a);var g=this.hasExpandingManager()&&this.expandingManager.isMultiDirectionalExpanding(f);if(d&&!this.isInAdSenseIFrame()&&g)var h=this.expandingManager.getExpandingDirection(b);if(d)this._adjustWindowElements(a,
true);if(d&&b.pushContents)this.expandingManager.startAnimation(b,true);else this.unclipFlashObject(b,c,e);if(d&&g)if(this.isInAdSenseIFrame())this.expandingManager.creativeToolset.expandWindow();else this.multiDirectionExpand(f,h)};RichMediaCreativeDisplayManager_56_03.prototype.multiDirectionExpand=function(a,b){try{this.setFlashVariable(this.creative.asVersion,a,"mde_expandedDirection",b)}catch(c){}};
RichMediaCreativeDisplayManager_56_03.prototype.collapseAsset=function(a){var b=this.getAsset(a);var c=b.collapsedWidth!=undefined?b.collapsedWidth:b.width;var e=b.collapsedHeight!=undefined?b.collapsedHeight:b.height;var d=this.creative.type==this.CREATIVE_TYPE_EXPANDING;if(d&&b.pushContents)this.expandingManager.startAnimation(b,false);else this.clipFlashObject(b,c,e,b.offsetTop,b.offsetRight,b.offsetBottom,b.offsetLeft);if(d)this._adjustWindowElements(a,false);var f=this.toObject("FLASH_"+a);var g=
this.hasExpandingManager()&&this.expandingManager.isMultiDirectionalExpanding(f);if(d&&g)if(this.isInAdSenseIFrame())this.expandingManager.creativeToolset.collapseWindow();else this.multiDirectionCollapse(f)};RichMediaCreativeDisplayManager_56_03.prototype.multiDirectionCollapse=function(a){try{this.setFlashVariable(this.creative.asVersion,a,"mde_expandedState","collapsed")}catch(b){}};
RichMediaCreativeDisplayManager_56_03.prototype.onMouseOver=function(a){try{var b=this.toObject("FLASH_"+a);this.setFlashVariable(this.creative.asVersion,b,"isMouseOver","1")}catch(c){}};RichMediaCreativeDisplayManager_56_03.prototype.onMouseOut=function(a){try{var b=this.toObject("FLASH_"+a);this.setFlashVariable(this.creative.asVersion,b,"isMouseOver","0")}catch(c){}};
RichMediaCreativeDisplayManager_56_03.prototype.scheduleCallbackOnLoad=function(a){a='dartCreativeDisplayManagers["'+this.creativeIdentifier+'"].'+a;this.registerPageLoadHandler(a,null)};RichMediaCreativeDisplayManager_56_03.prototype.scheduleDisplay=function(a,b,c){b=this._convertDuration(b);if(c)this._adjustWindowElements(a,true);if(b=="AUTO")this.registerTimeoutHandler(1000,"_autoStopPlaying('"+a+"')",this);else if(b>0)this.registerTimeoutHandler(eval(b)*1000,"stopDisplay('"+a+"')",this)};
RichMediaCreativeDisplayManager_56_03.prototype.tellCompanionAssetStop=function(a){this.dualAssetManager.tellCompanionAssetStop(a)};RichMediaCreativeDisplayManager_56_03.prototype.tellCompanionAssetStart=function(a){this.dualAssetManager.tellCompanionAssetStart(a)};RichMediaCreativeDisplayManager_56_03.prototype.tellCompanionAssetHide=function(a){this.dualAssetManager.tellCompanionAssetHide(a)};RichMediaCreativeDisplayManager_56_03.prototype.tellCompanionAssetShow=function(a){this.dualAssetManager.tellCompanionAssetShow(a)};
RichMediaCreativeDisplayManager_56_03.prototype.getAsset=function(a){for(var b in this.creative.assets)if(this.creative.assets[b].variableName==a)return this.creative.assets[b];return null};RichMediaCreativeDisplayManager_56_03.prototype.tellAssetHide=function(a){var b=this.getAssetType(a);if(b==this.ASSET_TYPE_OVERLAY)this.closePopupAsset(a);else this.stopDisplay(a)};RichMediaCreativeDisplayManager_56_03.prototype.tellAssetShow=function(a){this._startDisplay(a,false)};
RichMediaCreativeDisplayManager_56_03.prototype.tellAssetStart=function(a){if(this.isFlashScriptingSupported())this.playFlash(a)};RichMediaCreativeDisplayManager_56_03.prototype.tellAssetStop=function(a){var b=this.toObject("FLASH_"+a);if(b&&this.isFlashScriptingSupported())b.StopPlay()};RichMediaCreativeDisplayManager_56_03.prototype.tellAssetGotoFrame=function(a,b){var c=this.toObject("FLASH_"+a);if(c&&this.isFlashScriptingSupported())c.GotoFrame(b)};
RichMediaCreativeDisplayManager_56_03.prototype.isAssetPlaying=function(a){var b=this.toObject("FLASH_"+a);if(b&&this.isFlashScriptingSupported())return b.IsPlaying();return false};
RichMediaCreativeDisplayManager_56_03.prototype.replayAsset=function(a){var b=this.toObject("DIV_"+a);if(b&&b.style.visibility!="visible"){b.style.visibility="visible";var c=this.getAsset(a);if(c!=null){var e=this.toObject("FLASH_"+a);e.Rewind();e.StopPlay();this.scheduleDisplay(a,c.duration,true);if(c.isMainAsset){var d=this.getRenderingId(a);this.logEvent("Start","DISPLAY_TIMER",d)}}}};
RichMediaCreativeDisplayManager_56_03.prototype.openPopup=function(a,b,c,e){if(c)var d=window.open(a,b,c);else d=window.open(a,b);this.dartPopupArray[b]=d;if(eval(e))window.focus();return d};
RichMediaCreativeDisplayManager_56_03.prototype.notifyPreviewHandler=function(a,b){if(this.creative.debugEventsMode&&this.previewHandler)try{if(b=="startDisplay"){var c=this.generateGlobalCallback("replayAsset('"+a.variableName+"')",this);this.previewHandler.onAssetDisplayed("DIV_"+a.variableName,a.assetType,c)}else if(b=="stopDisplay")this.previewHandler.onBeforeAssetRemoved("DIV_"+a.variableName,a.assetType)}catch(e){}};
RichMediaCreativeDisplayManager_56_03.prototype.stopDisplay=function(a){var b=this.toObject("DIV_"+a);if(b.style.visibility=="hidden")return;var c=this.getAsset(a);this.notifyPreviewHandler(c,"stopDisplay");var e=this.toObject("FLASH_"+a);var d=this.creative.renderingId;if(c.isMainAsset)this.stopStandardTimers(d);this.flushCounters(d);if(!this.isAnyCompanionVisible(a))this.scheduleTurnOffEventBinFlushing(d,2);b.removeChild(e);b.style.visibility="hidden";this._adjustWindowElements(a,false)};
RichMediaCreativeDisplayManager_56_03.prototype.isAnyCompanionVisible=function(a){for(var b in this.assets)if(!this.isPartOfArrayPrototype(b)&&b!=a){var c=this.toObject("DIV_"+b);if(c&&c.style.visibility=="visible")return true}return false};RichMediaCreativeDisplayManager_56_03.prototype.addEntityProperties=function(a,b,c,e,d,f,g){this.pageElementsManager.addEntityProperties(a,b,c,e,d,f,g)};
RichMediaCreativeDisplayManager_56_03.prototype.doNotAdjustIFrame=function(a,b){this.pageElementsManager.doNotAdjustIFrame(a,b)};RichMediaCreativeDisplayManager_56_03.prototype.doNotAdjustObject=function(a,b){this.pageElementsManager.doNotAdjustObject(a,b)};RichMediaCreativeDisplayManager_56_03.prototype.getRenderingId=function(a){var b=a.split("_");return b.length>1?b[0]:null};
RichMediaCreativeDisplayManager_56_03.prototype.createFunctionCall=function(a,b){var c=a+"(";var e=0;for(var d=0;d<b.length;d++){if(e>0)c+=", ";c+='"'+b[d]+'"';e++}c+=")";return c};RichMediaCreativeDisplayManager_56_03.prototype._splitArgs=function(a){var b=new Array;var c=unescape(a);var e=c.split("#mtf#");for(var d=0;d<e.length;d++)b[d]=e[d];return b};
RichMediaCreativeDisplayManager_56_03.prototype._parseCommandString=function(a){var b=new Object;b.command=unescape(a.split("=")[0]);b.argString=unescape(a.split("=")[1]);var c=b.argString.split("#mtf#");b.argArray=new Array;for(var e=0;e<c.length;e++)b.argArray[e]=c[e]=="null"?null:c[e];return b};
RichMediaCreativeDisplayManager_56_03.prototype._startDisplay=function(a,b){var c=this.toObject("DIV_"+a);var e=this.toObject("FLASH_"+a);if(b)this._adjustWindowElements(a,true);if(c)c.style.visibility="visible";if(e&&this.isFlashScriptingSupported())this.playFlash(a);var d=this.creative.renderingId;if(e&&this.debugEventsMode){if(!this.dartDebugEventBin.getShouldFlush(d)){this.setShouldFlush(d,true);this.dartDebugEventBin.flushMetCounters(d)}}else if(e&&!this.previewMode&&!this.dartEventBin.getShouldFlush(d))this.setShouldFlush(d,
true)};RichMediaCreativeDisplayManager_56_03.prototype.playFlash=function(a){var b=this.toObject("FLASH_"+a);var c=this.getAsset(a);var e=c.assetType;if(this.isInternetExplorer())b.Play();else if(e=="float"||e=="reminder"||e=="banner"||e=="expando")if(c.conduitInitialized){if(b.TCurrentFrame("/")<=0)b.Play()}else this.registerTimeoutHandler(100,"playFlash('"+a+"')",this)};
RichMediaCreativeDisplayManager_56_03.prototype._autoStopPlaying=function(a){var b=this.toObject("FLASH_"+a);if(b&&this.isFlashScriptingSupported())if(b.PercentLoaded()==100&&!b.IsPlaying())this.stopDisplay(a);else this.registerTimeoutHandler(300,"_autoStopPlaying('"+a+"')",this)};RichMediaCreativeDisplayManager_56_03.prototype._adjustWindowElements=function(a,b){this.pageElementsManager._adjustWindowElements(a,b)};RichMediaCreativeDisplayManager_56_03.prototype.triggerPoliteDownload=function(){for(var a in this.assets)if(!this.isPartOfArrayPrototype(a))this.finishPoliteDownload(a)};
RichMediaCreativeDisplayManager_56_03.prototype.finishPoliteDownload=function(a){var b=this.toObject("FLASH_"+a);if(b&&typeof b.PercentLoaded!="undefined"&&b.PercentLoaded()>0&&this.getAsset(a).conduitInitialized)this.setFlashVariable(this.creative.asVersion,b,"mtfContinue","1");else{var c="dartCreativeDisplayManagers['"+this.creativeIdentifier+"'].finishPoliteDownload('"+a+"');";window.setTimeout(c,100)}};RichMediaCreativeDisplayManager_56_03.prototype.triggerDispatchScriptLoaded=function(){for(var a in this.assets)if(!this.isPartOfArrayPrototype(a))this.finishDispatchScriptLoaded(a)};
RichMediaCreativeDisplayManager_56_03.prototype.finishDispatchScriptLoaded=function(a){var b=this.toObject("FLASH_"+a);try{if(b&&typeof b.PercentLoaded!="undefined"&&b.PercentLoaded()>0&&typeof b.TCurrentFrame!="undefined"&&b.TCurrentFrame("/")>=0)this.setFlashVariable(this.creative.asVersion,b,"globalTemplateScriptLoaded","1");else{var c="dartCreativeDisplayManagers['"+this.creativeIdentifier+"'].finishDispatchScriptLoaded('"+a+"');";window.setTimeout(c,100)}}catch(e){c="dartCreativeDisplayManagers['"+
this.creativeIdentifier+"'].finishDispatchScriptLoaded('"+a+"');";window.setTimeout(c,100)}};RichMediaCreativeDisplayManager_56_03.prototype.unloadPopup=function(){var a=this.renderingId;if(a){this.flushCounters(a);this.setShouldFlush(a,false);this.stopStandardTimers(a)}};RichMediaCreativeDisplayManager_56_03.prototype.forceAnimation=function(a){var b=this.toObject("FLASH_"+a);var c=this.toObject("DIV_"+a);if(c.style.visibility=="visible"){b.Zoom(50);b.Zoom(0)}};
RichMediaCreativeDisplayManager_56_03.prototype.isFlashScriptingSupported=function(){return this.isWindows()||this.isMac()&&(this.isFirefox()||this.isSafari())};RichMediaCreativeDisplayManager_56_03.prototype.registerCreativeElement=function(a){this.rootElementArray[this.rootElementArray.length]=a};
RichMediaCreativeDisplayManager_56_03.prototype.removeChildNode=function(a,b){if(a.hasChildNodes()){var c=a.childNodes;for(var e=0;e<c.length;e++)this.removeChildNode(c[e],b)}else{var d=a.parentNode;d.removeChild(a);if(b!=d)this.removeChildNode(d,b)}};RichMediaCreativeDisplayManager_56_03.prototype.openPopupAsset=function(){if(this.overlay)this.overlay._openPopup()};RichMediaCreativeDisplayManager_56_03.prototype.closePopupAsset=function(){if(this.overlay)this.overlay._closePopup()};
RichMediaCreativeDisplayManager_56_03.prototype.registerOverlay=function(a){this.overlay=a};RichMediaCreativeDisplayManager_56_03.prototype.getAssetType=function(a){for(var b in this.creative.assets)if(this.creative.assets[b].variableName==a)return b;return null};RichMediaCreativeDisplayManager_56_03.prototype.setServedInIframe=function(a){this.servedInIframe=a};RichMediaCreativeDisplayManager_56_03.prototype.isServedInIframe=function(){return this.sourceIframe!=null};
RichMediaCreativeDisplayManager_56_03.prototype.setSourceIframe=function(a){this.sourceIframe=a};RichMediaCreativeDisplayManager_56_03.prototype.getSourceIframe=function(){return this.sourceIframe};function RichMediaEventBin_56_03(a,b){this.dartIntervalArray=b?new Array:new Array(10,20,50,120,240);this.dartEventBinCollection=new Array;this.dartRegistrationTime=null;this.dartMaxTimeMilliseconds=20*60*1000;this.dartCreativeIdentifier=a;this.timerAdjustments=new Array;this.dynamicServeId=null}
RichMediaEventBin_56_03.prototype=new RichMediaCore_56_03;RichMediaEventBin_56_03.prototype.setTimerAdjustment=function(a,b,c){var e=new Object;e.eventId=a;e.startAdjustmentTime=parseInt(b);e.stopAdjustmentTime=parseInt(c);this.timerAdjustments[a]=e};
RichMediaEventBin_56_03.prototype.registerEventBinUrl=function(a,b){if(!this.dartEventBinCollection[a]){var c=new Array;c["counter"]=new Array;c["timer"]=new Array;c["duration"]=new Array;c["nonCumulativeCounters"]=new Array;c["flushUrl"]=b;c["shouldFlush"]=true;this.dartEventBinCollection[a]=c;this.dartRegistrationTime=new Date;this.setFlushInterval(a)}};RichMediaEventBin_56_03.prototype.setDynamicServeId=function(a){this.dynamicServeId=a};
RichMediaEventBin_56_03.prototype.logMetEvent=function(a,b,c,e){if(this.dartEventBinCollection[c]&&b&&!isNaN(b))switch(a){case "Count":{this.processCounter(b,c,e);break}case "Start":{this.processStart(b,c);break}case "Stop":{this.processStopTimer(b,c);break}default:break}};
RichMediaEventBin_56_03.prototype.processCounter=function(a,b,c){var e=this.getNonCumulativeCountersArray(b);var d=this.getCounterArray(b);c=c&&(c=="true"||c==true);if(!c){if(!e[a])d[a]=1;e[a]=true}else{if(!d[a])d[a]=0;d[a]=d[a]+1}};RichMediaEventBin_56_03.prototype.processStart=function(a,b){var c=this.getTimerArray(b);if(!c[a]){var e=new Date;var d=this.timerAdjustments[a];if(d){var f=e.getTime()+d.startAdjustmentTime;e.setTime(f)}c[a]=e;this.processCounter(a,b,false)}};
RichMediaEventBin_56_03.prototype.processStopTimer=function(a,b){var c=this.getTimerArray(b);var e=this.getDurationArray(b);if(c[a]){var d=c[a];var f=new Date;var g=f.getTime()-d.getTime();if(g<0||g>this.dartMaxTimeMilliseconds)g=0;e[a]=e[a]?e[a]+g:g;c[a]=false;return true}return false};
RichMediaEventBin_56_03.prototype.flushMetCounters=function(a){if(this.dartEventBinCollection[a]&&this.getShouldFlush(a)){var b="";var c=this.getCounterArray(a);var e=this.getDurationArray(a);var d=this.getTimerArray(a);var f=1;if(this.isInAllowedTimeframe()){for(var g in c)if(!this.isPartOfArrayPrototype(g)){var h=this.processStopTimer(g,a);var i=c[g];if(!e[g])e[g]=0;var j=this.roundNumber(e[g]?parseFloat(String(e[g]/1000)):0);if(i>0||j>0){b+="eid"+f+"="+g+";";b+="ecn"+f+"="+i+";";b+="etm"+f+"="+
j+";"}c[g]=c[g]-i;e[g]=e[g]-j*1000;if(h)d[g]=new Date;f++}this.postData(b,a)}}};RichMediaEventBin_56_03.prototype.turnOffFlushing=function(a){this.flushMetCounters(a);this.setMetShouldFlush(false)};RichMediaEventBin_56_03.prototype.postData=function(a,b){if(a.length){var c=new Date;var e=this.splitActivity(a);for(var d=0;d<e.length;d++){var f=document.createElement("img");var g=e[d];f.src=this.getFlushUrl(b)+this.getDynamicServeKeyvalue()+"&timestamp="+c.getTime()+";"+g}}};
RichMediaEventBin_56_03.prototype.getDynamicServeKeyvalue=function(){return this.dynamicServeId?"rm_mid="+escape(this.dynamicServeId)+";":""};RichMediaEventBin_56_03.prototype.splitActivity=function splitActivity(b){var c=new Array;var e="etm";var d=950;for(var f=0;b.length>0;b=b.substr(f)){var g=b;var h=g.substr(0,d);f=h.lastIndexOf(e)+e.length;h=g.substr(0,f);g=g.substr(f);f+=g.indexOf(";")+1;c[c.length]=b.substr(0,f)}return c};
RichMediaEventBin_56_03.prototype.getCounterArray=function(a){var b=this.dartEventBinCollection[a];return b["counter"]};RichMediaEventBin_56_03.prototype.getTimerArray=function(a){var b=this.dartEventBinCollection[a];return b["timer"]};RichMediaEventBin_56_03.prototype.getDurationArray=function(a){var b=this.dartEventBinCollection[a];return b["duration"]};RichMediaEventBin_56_03.prototype.getNonCumulativeCountersArray=function(a){var b=this.dartEventBinCollection[a];return b["nonCumulativeCounters"]};
RichMediaEventBin_56_03.prototype.getFlushUrl=function(a){var b=this.dartEventBinCollection[a];return b["flushUrl"]};RichMediaEventBin_56_03.prototype.getShouldFlush=function(a){var b=this.dartEventBinCollection[a];return b["shouldFlush"]};RichMediaEventBin_56_03.prototype.setMetShouldFlush=function(a,b){var c=this.dartEventBinCollection[a];if(c)c["shouldFlush"]=b};
RichMediaEventBin_56_03.prototype.isInAllowedTimeframe=function(){var a=new Date;return!(a.getTime()-this.dartRegistrationTime.getTime()>this.dartMaxTimeMilliseconds)};RichMediaEventBin_56_03.prototype.roundNumber=function(a,b){b=b?b:0;return Math.round(a*Math.pow(10,b))/Math.pow(10,b)};RichMediaEventBin_56_03.prototype.setFlushInterval=function(a){for(var b=0;b<this.dartIntervalArray.length;b++){var c=this.dartIntervalArray[b]*1000;this.registerTimeoutHandler(c,"flushMetCounters('"+a+"')",this)}};
function InpageRenderer_56_03(a){this.flashUtil=new FlashUtil_56_03(a)}InpageRenderer_56_03.prototype=new RichMediaCore_56_03;
InpageRenderer_56_03.prototype.displayInpage=function(a,b){var c=a.assets[this.ASSET_TYPE_INPAGE];var e="dartCreativeDisplayManagers['"+a.creativeIdentifier+"'].onMouseOut('"+c.variableName+"');";var d="dartCreativeDisplayManagers['"+a.creativeIdentifier+"'].onMouseOver('"+c.variableName+"');";document.write('<div id="DIV_'+c.variableName+'" onmouseover="'+d+'" onmouseout="'+e+'" style="position:static;width:'+c.width+";visibility:visible;z-index:"+c.zIndex+";"+c.cssProperty+'">');var f=this.flashUtil.getObjectHtml("alt",
c.altText,"id","FLASH_"+c.variableName,"WIDTH",c.width,"HEIGHT",c.height,"movie",c.url,"quality","high","bgcolor",c.bgColor,"wmode",c.wmode,"name","FLASH_"+c.variableName,"swLiveConnect","TRUE","queryString",c.queryString);RichMediaCore_56_03.prototype.trackCsiEvent("fb");document.write(f);document.write("</div>");this.logThirdPartyFlashDisplayImpression(a,false);this.startDisplay(a,b)};
InpageRenderer_56_03.prototype.startDisplay=function(a,b){var c=a.assets[this.ASSET_TYPE_INPAGE];var e="FLASH_"+c.variableName;if(this.toObject(e)==null){if(this.callbackParameters[e]==null)this.callbackParameters[e]=this.createFunction("startDisplay",this,arguments);window.setTimeout(this.callbackParameters[e],100);return}b.fsHook(e);b.registerUrl(a.renderingId,a.adserverUrl)};function FlashUtil_56_03(a){this.creative=a}FlashUtil_56_03.prototype=new RichMediaCore_56_03;
FlashUtil_56_03.prototype.getObjectHtml=function(){var a=this.getArgs(arguments);return this.generateObj(a.objAttrs,a.params,a.embedAttrs)};
FlashUtil_56_03.prototype.getArgs=function(a){var b=new Object;b.embedAttrs=new Object;b.params=new Object;b.objAttrs=new Object;var c="";var e=false;for(var d=0;d<a.length;d=d+2){var f=a[d].toLowerCase();switch(f){case "codebase":case "pluginspage":case "type":case "classid":case "minversion":break;case "src":case "movie":b.params["movie"]=b.embedAttrs["src"]=a[d+1];break;case "querystring":c=a[d+1]=a[d+1]+"&br="+escape(this.getBrowser())+"&os="+escape(this.getOS());break;case "width":case "height":case "align":case "vspace":case "hspace":case "class":case "title":case "accesskey":case "name":case "id":case "tabindex":case "alt":case "onmouseover":case "onmouseout":b.embedAttrs[a[d]]=
b.objAttrs[a[d]]=a[d+1];break;case "swliveconnect":b.embedAttrs[a[d]]=a[d+1];break;case "wmode":e=this.isFlashFullScreenSupported(a[d+1]);b.embedAttrs[a[d]]=b.params[a[d]]=a[d+1];break;default:b.embedAttrs[a[d]]=b.params[a[d]]=a[d+1]}}c+="&isFlashFullScreenEnabled="+e;b.params["FlashVars"]=b.embedAttrs["FlashVars"]=c;b.objAttrs["classid"]="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";b.embedAttrs["type"]="application/x-shockwave-flash";b.params["allowScriptAccess"]="always";b.embedAttrs["allowScriptAccess"]=
"always";if(e){b.params["allowFullScreen"]="true";b.embedAttrs["allowFullScreen"]="true"}return b};
FlashUtil_56_03.prototype.generateObj=function(a,b,c){var e="";if(this.isInternetExplorer()){e+="<object ";for(var d in a)if(!this.isPartOfArrayPrototype(d))e+=d+'="'+a[d]+'" ';e+=">";for(d in b)if(!this.isPartOfArrayPrototype(d))e+='<param name="'+d+'" value="'+b[d]+'" /> '}e+="<embed ";for(d in c)if(!this.isPartOfArrayPrototype(d))e+=d+'="'+c[d]+'" ';e+=" ></embed>";if(this.isInternetExplorer())e+="</object>";return e};
FlashUtil_56_03.prototype.getBrowser=function(){if(this.isInternetExplorer())return"ie";else if(this.isFirefox())return"ff";else if(this.isSafari())return"sf";else if(this.isChrome())return"cr";else return"NOT_SUPPORTED"};FlashUtil_56_03.prototype.getOS=function(){if(this.isWindows())return"win";if(this.isMac())return"mac";else return"NOT_SUPPORTED"};
FlashUtil_56_03.prototype.isFlashFullScreenSupported=function(a){var b=this.getPluginInfo();var c=this.creative.requiredPlayerVersion;if(c>5&&this.creative.fullScreenEnabled)if(b>=9.115||b>=9.28&&a=="window")return true;return false};function ScriptCreativeRenderer_56_03(){}ScriptCreativeRenderer_56_03.prototype=new RichMediaCore_56_03;
ScriptCreativeRenderer_56_03.prototype.showCreative=function(a){var b=a.type;var c=new RichMediaCreativeDisplayManager_56_03(a);dartCreativeDisplayManagers[a.creativeIdentifier]=c;if(b==this.CREATIVE_TYPE_INPAGE){var e=new InpageRenderer_56_03(a);e.displayInpage(a,c)}else if(b==this.CREATIVE_TYPE_EXPANDING){e=new ScriptExpandingRenderer_56_03(a);var d=new ExpandingManager_56_03(a,c);d.init();c.setExpandingManager(d);e.displayExpanding(a,c,d)}else if(b==this.CREATIVE_TYPE_FLOATING){var f=a.assets[this.ASSET_TYPE_FLOATING];
var g=new FloatingManager_56_03(a,c);if(this._isValidStartTime(f.startTime))c.registerTimeoutHandler(eval(f.startTime)*1000,"displayFloatingFlash()",g)}else if(b==this.CREATIVE_TYPE_INPAGE_WITH_OVERLAY){var h=new InpageRenderer_56_03(a);h.displayInpage(a,c);var i=new RichMediaOverlay_56_03(a,c);c.registerOverlay(i);i.scheduleOverlay()}else if(b==this.CREATIVE_TYPE_INPAGE_WITH_FLOATING){h=new InpageRenderer_56_03(a);h.displayInpage(a,c);f=a.assets[this.ASSET_TYPE_FLOATING];g=new FloatingManager_56_03(a,
c);c.setFloatingManager(g);if(this._isValidStartTime(f.startTime))c.registerTimeoutHandler(eval(f.startTime)*1000,"displayFloatingFlash()",g)}if(c.isFlashScriptingSupported()){c.scheduleCallbackOnLoad("triggerPoliteDownload()");c.triggerDispatchScriptLoaded()}};ScriptCreativeRenderer_56_03.prototype.showOnPageLoad=function(a){var b=dartRichmediaCreatives[a];this.showCreative(b)};
ScriptCreativeRenderer_56_03.prototype.show=function(){this.registerPageLoadHandler("pageLoaded()",this);for(var a=0;a<dartRichmediaCreatives.length;a++){var b=dartRichmediaCreatives[a];if(typeof b.isProcessed=="undefined"||!b.isProcessed){if(b.type==this.CREATIVE_TYPE_FLOATING)this.registerPageLoadHandler("showOnPageLoad("+a+")",this);else this.showCreative(b);b.isProcessed=true}}};if(dartRichmediaCreatives!=undefined)(new ScriptCreativeRenderer_56_03).show();RichMediaCore_56_03.prototype.trackCsiEvent("ge");