/*
 * generated by Xtext
 */
package net.sf.smbt.osc;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class OscDslRuntimeModule extends net.sf.smbt.osc.AbstractOscDslRuntimeModule {

}
