/*
* generated by Xtext
*/
package net.sf.smbt.osc.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import net.sf.smbt.osc.services.OscDslGrammarAccess;

public class OscDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private OscDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected net.sf.smbt.osc.parser.antlr.internal.InternalOscDslParser createParser(XtextTokenStream stream) {
		return new net.sf.smbt.osc.parser.antlr.internal.InternalOscDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "EzModel";
	}
	
	public OscDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(OscDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
