/*
 * generated by Xtext
 */
package net.sf.smbt.osc.ui;

import net.sf.smbt.osc.ui.labeling.KeywordSyntaxHgihlightConfig;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;

/**
 * Use this class to register components to be used within the IDE.
 */
public class OscDslUiModule extends net.sf.smbt.osc.ui.AbstractOscDslUiModule {
	public OscDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return KeywordSyntaxHgihlightConfig.class;
	}
	/*
	// contributed by org.eclipse.xtext.ui.generator.refactoring.RefactorElementNameFragment
	public Class<? extends org.eclipse.xtext.ui.refactoring.ui.IRenameSupport.Factory> bindIRenameSupport$Factory() {
		return org.eclipse.xtext.ui.refactoring.ui.DefaultRenameSupport.Factory.class;
	}
	*/
}
